### ISSUE TITLE
Todo App 명세서 작성

### ISSUE THREAD

**Issue by ymymmz9** [ymymmz9/Pre_Project_0#3]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] CRA를 이용한 앱 생성
2. [x] 페이지와 하위 컴포넌트 생성
3. [ ] 상태관리 함수 생성
4. [ ] CSS 작업

### 예상 작업 시간
ex) 3h
